#!/usr/bin/env node
/**
 * Generate subgraph/src/config.ts from env vars before each build/deploy.
 *
 * Env:
 *   RELAYER_ADDRESSES — comma-separated 0x addresses (case-insensitive).
 *                       Agents whose Registered event has the relayer as
 *                       owner, OR whose NFT was transferred FROM one of
 *                       these addresses, get registrationOrigin="RELAYER".
 *
 * Output: src/config.ts is rewritten on every run. The file is gitignored
 * because its contents are deployment-specific (per-chain relayer wallet).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'src', 'config.ts');

const raw = process.env.RELAYER_ADDRESSES ?? '';
const valid = [];
for (const part of raw.split(',').map((s) => s.trim()).filter(Boolean)) {
  if (!/^0x[0-9a-fA-F]{40}$/.test(part)) {
    console.error(`gen-config: ignoring invalid address "${part}"`);
    continue;
  }
  valid.push(part.toLowerCase());
}

if (valid.length === 0) {
  console.warn('gen-config: RELAYER_ADDRESSES empty or unset — no agents will be tagged as RELAYER-registered');
}

const body = `// AUTO-GENERATED by scripts/gen-config.mjs — do not edit by hand.
// Source: RELAYER_ADDRESSES env var (comma-separated, lowercased).
//
// Used by identity-registry.ts to tag Agent.registrationOrigin = "RELAYER"
// for agents whose ERC-8004 mint OR onward NFT transfer came from one of
// these addresses.

export const KNOWN_RELAYER_ADDRESSES: string[] = [
${valid.map((a) => `  "${a}"`).join(',\n')}${valid.length > 0 ? ',' : ''}
]
`;

fs.writeFileSync(OUT, body);
console.log(`gen-config: wrote ${valid.length} relayer address(es) to ${path.relative(process.cwd(), OUT)}`);
